### ISSUE TITLE
Firebase Authentication with User Roles

### ISSUE THREAD

**Issue by zacktraczyk** [CruzHacks/cruzhacks-2024-backend#1]
Well we do need firebase functions after all. We can reference our [old backend](https://github.com/CruzHacks/cruzhacks-backend) for some of the functionality but I still think it is worth starting a new repo to address some of the security vulnerabilities and deprecated code.

I found [this tutorial](https://www.toptal.com/firebase/role-based-firebase-authentication) that is super helpful for setting up user roles in firebase with authentication. The frontend part is in Angular which you can reference to use in React, or we can definitely try a different approach or use a different article but these seems like a great place to start.

**UPDATE 10/30:** I have been playing around a bit with protected routing in the frontend and it is pretty cumbersome to get/update custom user roles. I found [this article](https://medium.com/firebase-developers/patterns-for-security-with-firebase-supercharged-custom-claims-with-firestore-and-cloud-functions-bb8f46b24e11) that has a better approach to mirror changes in firestore

#### TODO:
- [x] Create cruzhacks-backend-2024 repo (preferably use [cruzhacks-2024](https://github.com/CruzHacks/cruzhacks-2024) monorepo but there is an issue that needs to be resolved with that first)
- [x] Firebase login / Firebase init functions (you are all added as admins to cruzhacks-2024-Development, please use this Firebase project; follow the tutorial or make sure to use typescript)
- [x] Create express middleware
- [ ] Create sample endpoints
- [ ] Test (and if possible add testing framework)

#### OPTIONAL TODO:
- [ ] Setup deploy targets for development and production (can wait to do this if help needed, can be tricky but you can look at [cruzhacks-2024-website](https://github.com/CruzHacks/cruzhacks-2024-website) for example)
- [ ] Create Github Actions to autodeploy on PRs and merge
