### ISSUE TITLE
Create Firebase Firestore Security Rules

### ISSUE THREAD

**Issue by zacktraczyk** [CruzHacks/cruzhacks-2024-backend#4]
# Scope

Firestore secures user data by [using Firestore rules](https://firebase.google.com/docs/firestore/security/get-started). Since we are mostly going for an api-less backend using the firebase javasscript sdk it is super essential these security rules are tight or else we open our backend to malicious users.

Please do some research into firestore rules and secure the existing collections based on role and authentication. Update rules in the already existing `firestore.rules` document.

# TODO:

- [ ] Research [firestore security](https://firebase.google.com/docs/firestore/security/rules-structure#hierarchical_data)
- [ ] Secure existing collections
    - [ ] Secure `users` collection and `users/{email}` documents
        - [ ] Secure `user_items` subcollection
            - [ ]  Secure `application` document and `application/sections` subcollection
            - [ ] Secure `user_role` document
