### ISSUE TITLE
Create ApplicationSchema

### ISSUE THREAD

**Issue by zacktraczyk** [CruzHacks/cruzhacks-2024-backend#6]
# Scope

Make sure to go refine the `applicationSchema` to validate each field as strictly as possible. For example, age cannot be less than 0 nor greater than 120 and it should be a number. Include error messages that address these data format violations.

Go through [the figma registration form](https://www.figma.com/file/IXAajiFoWwcPU70DFs6hRt/Site-Architecture?type=design&node-id=0-1&mode=design&t=wXCUom0FsIiawHVg-0) and make sure that all the form data is represented as closely as possible. Edit the `schema.ts` to reflect this object.

## TODO:

- [ ] Make sure object can express all form fields
- [ ] Ensure correct data types (as closely)
- [ ] Add error messages [with zod](https://zod.dev/?id=error-handling)
